module.exports = {
  SAFE_ASCENT_RATE_MPS: 0.3,
  RAPID_ASCENT_THRESHOLD_MPS: 0.6,
  MODERATE_N2_THRESHOLD: 0.45,
  HIGH_N2_THRESHOLD: 0.6,
  NARCOSIS_DEPTH_THRESHOLD_M: 30,
  AIR_SUPPLY_WARNING_PCT: 25,
  AIR_SUPPLY_CRITICAL_PCT: 10,
};
